baseURL = "/"
languageCode = "en-us"
title = "Shayan Hosseini"
theme = "hugo-xmin"
footnotereturnlinkcontents = "↩"

[[menu.main]]
    name = "About"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
[[menu.main]]
    name = "Academics"
    url = "/academics/"
    weight = 3